name: Java CI with Maven and JavaFX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install X11 Forwarding Dependencies
      run: sudo apt-get update && sudo apt-get install -y libxext6 libxrender1 libxtst6 libxi6

    - name: Install JavaFX
      run: |
        mkdir -p $HOME/openjfx
        wget -q -O $HOME/openjfx/javafx-sdk-17.zip https://gluonhq.com/download/javafx-17-sdk-linux/
        unzip -q $HOME/openjfx/javafx-sdk-17.zip -d $HOME/openjfx
        export PATH="$PATH:$HOME/openjfx/javafx-sdk-17/lib"

    - name: Cache Maven Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

    - name: Build with Maven
      run: ./mvnw -B package

    - name: Run JavaFX Application
      env:
        DISPLAY: ${{ steps.xvfb.outputs.DISPLAY }}
      run: |
        java --module-path $HOME/openjfx/javafx-sdk-17/lib --add-modules javafx.controls,javafx.fxml -jar target/your-javafx-application.jar
